---
- name: nginx group add
  command: groupadd nginx

- name: nginx user add
  command: useradd -g nginx nginx

- name: nginx user no login
  command: usermod -s /bin/false nginx

- name: nginx download
  command: chdir={{ usr_src_dir }} wget http://nginx.org/download/nginx-1.7.10.tar.gz

- name: nginx tar archive resolve
  command: chdir={{ usr_src_dir }} tar zxvf nginx-1.7.10.tar.gz

- name: nginx sticky download
  command: chdir={{ usr_src_dir }}/nginx-1.7.10 git clone https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng.git

- name: nginx configure
  command: chdir={{ usr_src_dir }}/nginx-1.7.10 ./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-http_spdy_module --with-cc-opt='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --add-module={{ usr_src_dir }}/nginx-1.7.10/nginx-sticky-module-ng

- name: nginx make
  command: chdir={{ usr_src_dir }}/nginx-1.7.10 make

- name: nginx make install
  command: chdir={{ usr_src_dir }}/nginx-1.7.10 make install

- name: nginx init file create
  template: src=roles/nginx/templates/nginx dest=/etc/init.d/nginx owner=root group=root mode=755

- name: nginx config replace
  template: src=roles/nginx/templates/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=644

- name: nginx cache dir create
  command: mkdir /var/cache/nginx

- name: nginx cache dir chown
  command: chown nginx:nginx /var/cache/nginx

- name: set auto start nginx
  command: chkconfig nginx on

- name: restart nginx
  command: service nginx restart
