---
- name: epel install
  yum: name=epel-release state=present

- name: Java 1.8.0 install
  yum: name=java-1.8.0-openjdk state=present

- name: python-tools install
  yum: name=python-setuptools state=present

- name: pip install
  command: easy_install pip

- name: awscli install
  command: pip install awscli
  
- name: Check if selinux is installed
  command: getenforce
  ignore_errors: True
  register: command_result

- name: Install libselinux-python
  yum: name={{ item }}
  with_items:
    - libselinux-python
  when: command_result|success and command_result.stdout != 'Disabled'
